version: "3.8"

services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN_NAME:-docker.localhost}`)"
      - "traefik.http.routers.whoami.middlewares=serve-pretty-errors"

networks:
  proxy:
    external: true
