version: "3.7"

services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      #- "traefik.docker.network=proxy"
      # - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN_NAME:-docker.localhost}`)"
      # - "traefik.http.routers.whoami.tls=true"
      # - "traefik.http.routers.whoami.entrypoints=websecure"

networks:
  proxy:
    external: true
